### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by doisyg** [01org/vpx-image-transport#15]
Hello,
This project seems perfect for our usage (Robots powered by NUC with two realsense r200 camera and ROS).
But I can't manage to build this package, I get the following error:

`src/vpx-image-transport/src/streamer/webm-tools.patch:103: new blank line at EOF.
+
vpx-image-transport/src/streamer/CMakeFiles/webm-tools.dir/build.make:98: recipe for target 'vpx-image-transport/src/streamer/third_party/webm-tools/src/webm-tools-stamp/webm-tools-patch' failed
make[2]: *** [vpx-image-transport/src/streamer/third_party/webm-tools/src/webm-tools-stamp/webm-tools-patch] Error 1
`

**Comment by doisyg** [comment]
The patch webm-tools-patch seems outdated, anybody knows how to fix this in a stable way?
@tingshao and @minggangw ?

**Comment by tingshao** [comment]
It seems the patch failed due to webm-tools updated. I will update the CMakeList.txt to stick to the working version of webm-tools.

**Comment by doisyg** [comment]
Hi,
Still cannot build successfully

`ws/src/vpx-image-transport/src/vpx_publisher.cpp: In member function ‘void vpx_image_transport::VPXPublisher::configCallback(vpx_image_transport::VPXPublisher::Config&, uint32_t)’:
ws/src/vpx-image-transport/src/vpx_publisher.cpp:42:8: error: ‘struct vpx_streamer::EncoderConfig’ has no member named ‘target_bitrate’
   conf.target_bitrate = config.target_bitrate;
        ^
vpx-image-transport/CMakeFiles/vpx_image_transport.dir/build.make:62: recipe for target 'vpx-image-transport/CMakeFiles/vpx_image_transport.dir/src/vpx_publisher.cpp.o' failed
make[2]: *** [vpx-image-transport/CMakeFiles/vpx_image_transport.dir/src/vpx_publisher.cpp.o] Error 1
CMakeFiles/Makefile2:14498: recipe for target 'vpx-image-transport/CMakeFiles/vpx_image_transport.dir/all' failed
make[1]: *** [vpx-image-transport/CMakeFiles/vpx_image_transport.dir/all] Error 2
`

**Comment by doisyg** [comment]
I think there is still a version issue @tingshao

**Comment by tingshao** [comment]
@doisyg a new PR may fixed your issue, please try it:
https://github.com/01org/vpx-image-transport/pull/17

**Comment by doisyg** [comment]
Working! Thanks a lot
